/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Usuario;
import Clases.Club;
import Clases.Federacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author enrique
 */
public class AdministracionClubs extends javax.swing.JFrame {

    /**
     * Creates new form AdmistracionClubs
     */
    public AdministracionClubs(MenuAdmin menuAdmin) {
        initComponents();
        this.menuAdmin = menuAdmin;
        this.crearClub = new CrearClub(this);
        this.verJugadores = new VerJugadoresClub(this);
        this.gestionarEntrenadores = new GestionarEntrenador(this);
        this.gestionarGerente = new GestionarGerente(this);
        this.añadirGerente = new AñadirGerente(this);
        añadirGerenteButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CrearClub = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        verJugadoresButton = new javax.swing.JButton();
        VerEntrenadores = new javax.swing.JButton();
        JListClubes = new java.awt.List();
        nombreClub = new javax.swing.JLabel();
        nombreGerente = new javax.swing.JLabel();
        entrenador1Club = new javax.swing.JLabel();
        entrenador2Club = new javax.swing.JLabel();
        gestionarGerenteButton = new javax.swing.JButton();
        añadirGerenteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Volver.setText("Volver");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverMouseClicked(evt);
            }
        });

        jLabel1.setText("Lista de clubes:");

        CrearClub.setText("Crear club");
        CrearClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearClubMouseClicked(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Gerente:");

        jLabel4.setText("Entrenador:");

        verJugadoresButton.setText("Ver jugadores");
        verJugadoresButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verJugadoresButtonMouseClicked(evt);
            }
        });

        VerEntrenadores.setText("Gestionar entrenador");
        VerEntrenadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerEntrenadoresMouseClicked(evt);
            }
        });

        JListClubes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JListClubesItemStateChanged(evt);
            }
        });

        gestionarGerenteButton.setText("Gestionar gerente");
        gestionarGerenteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionarGerenteButtonMouseClicked(evt);
            }
        });

        añadirGerenteButton.setText("Añadir gerente");
        añadirGerenteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirGerenteButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CrearClub))
                            .addComponent(Volver)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JListClubes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreClub)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(nombreGerente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(añadirGerenteButton))
                                            .addComponent(gestionarGerenteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(entrenador1Club))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(entrenador2Club)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(verJugadoresButton)
                .addGap(18, 18, 18)
                .addComponent(VerEntrenadores)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearClub, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nombreClub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombreGerente)
                            .addComponent(gestionarGerenteButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(entrenador1Club)
                            .addComponent(añadirGerenteButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entrenador2Club))
                    .addComponent(JListClubes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verJugadoresButton)
                    .addComponent(VerEntrenadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(Volver)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseClicked
        this.setVisible(false);
        menuAdmin.setFederaciones(federacionesList);
        menuAdmin.setUsuario(usuario);
        menuAdmin.setVisible(true);
    }//GEN-LAST:event_VolverMouseClicked

    private void CrearClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearClubMouseClicked
        this.setVisible(false);
        crearClub.setFederaciones(federacionesList);
        crearClub.setLabels();
        crearClub.setVisible(true);
    }//GEN-LAST:event_CrearClubMouseClicked

    private void VerEntrenadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerEntrenadoresMouseClicked
        this.setVisible(false);
        gestionarEntrenadores.setClub(clubSelected);
        gestionarEntrenadores.setClubes(clubesList);
        gestionarEntrenadores.setLabels();
        gestionarEntrenadores.setVisible(true);
    }//GEN-LAST:event_VerEntrenadoresMouseClicked

    private void verJugadoresButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verJugadoresButtonMouseClicked
        this.setVisible(false);
        verJugadores.setClubes(clubesList);
        verJugadores.setUsuario(usuario);
        verJugadores.setClub(clubSelected);
        verJugadores.setLabels();
        verJugadores.setVisible(true);
    }//GEN-LAST:event_verJugadoresButtonMouseClicked

    private void JListClubesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JListClubesItemStateChanged
        clubSelected = clubesList.get(JListClubes.getSelectedIndex());
        nombreClub.setText(clubSelected.getNombre());
        nombreGerente.setText(clubSelected.getGerente().getNombre() + " " + clubSelected.getGerente().getApellidos());
        entrenador1Club.setText(clubSelected.getEntrenador().getNombre() + " " + clubSelected.getEntrenador().getApellidos());
        clubSelected.getGerente().verDatos();
        if(!clubSelected.getGerente().isExiste())
        {
            gestionarGerenteButton.setVisible(false);
            añadirGerenteButton.setVisible(true);
        }
    }//GEN-LAST:event_JListClubesItemStateChanged

    private void gestionarGerenteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionarGerenteButtonMouseClicked
        if (clubSelected == null)
            JOptionPane.showMessageDialog(null, "Selecciona un club");
        else
        {
            this.setVisible(false);
            gestionarGerente.setClubes(clubesList);
            gestionarGerente.setClub(clubSelected);
            gestionarGerente.setLabels();
            gestionarGerente.setVisible(true);
        }
    }//GEN-LAST:event_gestionarGerenteButtonMouseClicked

    private void añadirGerenteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirGerenteButtonMouseClicked
        añadirGerente.setVisible(true);
        añadirGerente.setClubes(clubesList);
        añadirGerente.setClub(clubSelected);
    }//GEN-LAST:event_añadirGerenteButtonMouseClicked

    public void setUsuario(Usuario usu)
    {
        usuario = usu;
    }
    
    public void setFederaciones(ArrayList<Federacion> federaciones)
    {
        federacionesList = federaciones;
    }
    
    public void setClubes(ArrayList<Club> clubes)
    {
        clubesList = clubes;    
    }
    
    public void setLabels ()
    {
        clubesList.clear();
        for(int i = 0; i < federacionesList.size(); i++)
            for(int j = 0; j < federacionesList.get(i).getClubesList().size(); j++)
            {
                clubesList.add(federacionesList.get(i).getClubesList().get(j));
            }
        
        JListClubes.removeAll();
        for (int i = 0; i < clubesList.size(); i++)
        {
            JListClubes.add(clubesList.get(i).getNombre(), i);
        }
        gestionarGerenteButton.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearClub;
    private java.awt.List JListClubes;
    private javax.swing.JButton VerEntrenadores;
    private javax.swing.JButton Volver;
    private javax.swing.JButton añadirGerenteButton;
    private javax.swing.JLabel entrenador1Club;
    private javax.swing.JLabel entrenador2Club;
    private javax.swing.JButton gestionarGerenteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nombreClub;
    private javax.swing.JLabel nombreGerente;
    private javax.swing.JButton verJugadoresButton;
    // End of variables declaration//GEN-END:variables
    private MenuAdmin menuAdmin;
    private GestionarEntrenador gestionarEntrenadores;
    private VerJugadoresClub verJugadores;
    private CrearClub crearClub;
    private GestionarGerente gestionarGerente;
    private AñadirGerente añadirGerente;
    private ArrayList<Federacion> federacionesList = new ArrayList<Federacion>();
    private ArrayList<Club> clubesList = new ArrayList<Club>();
    private Usuario usuario;
    private Club clubSelected;
}
