/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Club;
import Clases.Entrenador;
import Clases.Gerente;
import Clases.Usuario;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author enrique
 */
public class AñadirEntrenador extends javax.swing.JFrame {

    /**
     * Creates new form AñadirGerente
     */
    public AñadirEntrenador(AdministracionClubs administracionClubs) {
       initComponents();
       this.administracionClubs = administracionClubs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        añadirButton = new javax.swing.JButton();
        nombreGerente = new javax.swing.JTextField();
        apellidosGerente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fechaNacimientoText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellidos:");

        añadirButton.setText("Añadir");
        añadirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirButtonMouseClicked(evt);
            }
        });

        jLabel5.setText("Fecha de nacimiento:");

        jLabel6.setText("Formato DD/MM/AAAA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(añadirButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(fechaNacimientoText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(apellidosGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fechaNacimientoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(69, 69, 69)
                .addComponent(añadirButton)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirButtonMouseClicked
        
        if(ComprobarFormatoFecha(fechaNacimientoText.getText()))
        {
            club.getEntrenador().setDatos( nombreGerente.getText(), apellidosGerente.getText(), club.getNombre(), ConvertirFecha(fechaNacimientoText.getText()), true);
            administracionClubs.setClubes(clubesList);
            administracionClubs.setLabels();
            this.setVisible(false);
        } 
    }//GEN-LAST:event_añadirButtonMouseClicked

    public void setClubes(ArrayList<Club> clubes)
    {
        clubesList = clubes;    
    }
    
    public void setClub(Club _club)
    {
        club = _club;
    }
    
    public Date ConvertirFecha(String _fecha)
    {
        System.out.println(_fecha);
        int dia = Integer.parseInt(_fecha.substring(0, 2));
        int mes = Integer.parseInt(_fecha.substring(3, 5))-1;
        int anyo = Integer.parseInt(_fecha.substring(6, 10))-1900;
        
        Date fecha = new Date(anyo,mes,dia);
        
        System.out.println("Dia: " + dia);
        System.out.println("Mes: " + mes);
        System.out.println("Anyo: " + anyo);
        
        return fecha;
    }
    
    public boolean ComprobarFormatoFecha(String fecha)
    {
        boolean correcto = false;
        
        if(fecha.substring(2, 3).equals("/") && fecha.substring(5, 6).equals("/") && fecha.length() == 10)
        {
            int dia = Integer.parseInt(fecha.substring(0, 2));
            int mes = Integer.parseInt(fecha.substring(3, 5))-1;
            int anyo = Integer.parseInt(fecha.substring(6, 10))-1900;
            
            if((1 <= dia && 31 >= dia) && (0 <= mes && 11 >= mes))
                 correcto = true;
            else
                JOptionPane.showMessageDialog(null, "Introduce bien la fecha por favor");
        }
            
        else
            JOptionPane.showMessageDialog(null, "Introduce bien la fecha por favor");
        
        return correcto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosGerente;
    private javax.swing.JButton añadirButton;
    private javax.swing.JTextField fechaNacimientoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nombreGerente;
    // End of variables declaration//GEN-END:variables
    AdministracionClubs administracionClubs;
    private ArrayList<Club> clubesList = new ArrayList<Club>();
    private Club club;
    private Entrenador e;
}

