/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Club;
import Clases.Torneo;
import Clases.Usuario;
import java.util.ArrayList;

/**
 *
 * @author enrique
 */
public class ConfigurarTorneo extends javax.swing.JFrame {

    /**
     * Creates new form ConfigurarTorneo
     */
    public ConfigurarTorneo(AdministracionTorneos administracionTorneos) {
        initComponents();
        this.administracionTorneos = administracionTorneos;
        this.cuadro4 = new Cuadro4 (this);
        this.cuadro8 = new Cuadro8 (this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jugadoresJList = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        clubLabel = new javax.swing.JLabel();
        cuadroTorneoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        volverButton.setText("Volver");
        volverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Participantes:");

        jugadoresJList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jugadoresJListItemStateChanged(evt);
            }
        });

        jLabel2.setText("Club:");

        jLabel3.setText("Nombre:");

        nombreLabel.setText("jLabel4");

        clubLabel.setText("jLabel4");

        cuadroTorneoButton.setText("Ver cuadro torneo");
        cuadroTorneoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuadroTorneoButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugadoresJList, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(clubLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreLabel))
                            .addComponent(cuadroTorneoButton)))
                    .addComponent(jLabel1)
                    .addComponent(volverButton))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jugadoresJList, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(volverButton)
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombreLabel))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(clubLabel))
                        .addGap(43, 43, 43)
                        .addComponent(cuadroTorneoButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugadoresJListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jugadoresJListItemStateChanged
        numJugadorSelected = jugadoresJList.getSelectedIndex();
        jugadorSelected = torneo.getJugadoresList().get(numJugadorSelected);
        nombreLabel.setText(jugadorSelected.getNombre() + " " + jugadorSelected.getApellidos());
        clubLabel.setText(jugadorSelected.getClub());
    }//GEN-LAST:event_jugadoresJListItemStateChanged

    private void cuadroTorneoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuadroTorneoButtonMouseClicked

            if(torneo.getNumJugadores() == 4)
            {
                cuadro4.setTorneoSelected(torneo);
                cuadro4.setLabels();
                cuadro4.setVisible(true);
            }
            else if(torneo.getNumJugadores() == 8)
            {
                cuadro8.setTorneoSelected(torneo);
                cuadro8.setLabels();
                cuadro8.setVisible(true);
            }          
    }//GEN-LAST:event_cuadroTorneoButtonMouseClicked

    private void volverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMouseClicked
        this.setVisible(false);
        administracionTorneos.setVisible(true);
    }//GEN-LAST:event_volverButtonMouseClicked

    public void setClubes(ArrayList<Club> clubes)
    {
        clubesList = clubes;    
    }
    
    public void setTorneos(ArrayList<Torneo> torneos)
    {
        torneosList = torneos;
    }
    
    public void setTorneoSelected(Torneo tor)
    {
        torneo = tor;
    }
    
    public void setLabels ()
    {
        jugadoresJList.removeAll();
        System.out.println("Size: " + torneosList.size());
        for(int i = 0; i < torneo.getJugadoresList().size(); i++)
        {
            jugadoresJList.add(torneo.getJugadoresList().get(i).getNombre(), i);
        }
                
        if(torneo.isInscripcionAbierta())
        {
            cuadroTorneoButton.setVisible(false);
        }
        else
            cuadroTorneoButton.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clubLabel;
    private javax.swing.JButton cuadroTorneoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private java.awt.List jugadoresJList;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
    private AdministracionTorneos administracionTorneos;
    private Cuadro4 cuadro4;
    private Cuadro8 cuadro8;
    private ArrayList<Torneo> torneosList = new ArrayList<Torneo>();
    private ArrayList<Club> clubesList = new ArrayList<Club>();
    private int torneoSelected;
    private Torneo torneo;
    private Usuario jugadorSelected;
    private int numJugadorSelected;
}
