/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Torneo;

/**
 *
 * @author enrique
 */
public class Cuadro8 extends javax.swing.JFrame {

    /**
     * Creates new form Cuadro8
     */
    public Cuadro8(ConfigurarTorneo configurarTorneo) {
        initComponents();
        this.configurarTorneo = configurarTorneo;
        this.admin = true;
        simular1Button.setVisible(true);
        simular2Button.setVisible(true);
        simular3Button.setVisible(true);
        simular4Button.setVisible(true);
        simular5Button.setVisible(false);
        simular6Button.setVisible(false);
        simular7Button.setVisible(false);
    }
    
    public Cuadro8() {
        initComponents();
        this.admin = false;
        simular1Button.setVisible(false);
        simular2Button.setVisible(false);
        simular3Button.setVisible(false);
        simular4Button.setVisible(false);
        simular5Button.setVisible(false);
        simular6Button.setVisible(false);
        simular7Button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jugador1Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jugador2Label = new javax.swing.JLabel();
        jugador3Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jugador4Label = new javax.swing.JLabel();
        jugador7Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jugador8Label = new javax.swing.JLabel();
        jugador5Label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jugador6Label = new javax.swing.JLabel();
        volverButton = new javax.swing.JButton();
        semifinal1Jugador1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        semifinal2Jugador1 = new javax.swing.JLabel();
        semifinal2Jugador2 = new javax.swing.JLabel();
        semifinal1Jugador2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        finalJugador1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        finalJugador2 = new javax.swing.JLabel();
        puntosJugador1 = new javax.swing.JLabel();
        puntosJugador2 = new javax.swing.JLabel();
        puntosJugador3 = new javax.swing.JLabel();
        puntosJugador4 = new javax.swing.JLabel();
        puntosJugador5 = new javax.swing.JLabel();
        puntosJugador6 = new javax.swing.JLabel();
        puntosJugador7 = new javax.swing.JLabel();
        puntosJugador8 = new javax.swing.JLabel();
        puntosJugador1Semifinal2 = new javax.swing.JLabel();
        puntosJugador2Semifinal2 = new javax.swing.JLabel();
        puntosJugador1Semifinal1 = new javax.swing.JLabel();
        puntosJugador2Semifinal1 = new javax.swing.JLabel();
        puntosFinal1 = new javax.swing.JLabel();
        puntosFinal2 = new javax.swing.JLabel();
        simular1Button = new javax.swing.JButton();
        simular6Button = new javax.swing.JButton();
        simular2Button = new javax.swing.JButton();
        simular5Button = new javax.swing.JButton();
        simular3Button = new javax.swing.JButton();
        simular4Button = new javax.swing.JButton();
        simular7Button = new javax.swing.JButton();

        jugador1Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jugador1Label.setText("jLabel1");

        jLabel1.setText("vs.");

        jugador2Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jugador2Label.setText("jLabel2");

        jugador3Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jugador3Label.setText("jLabel2");

        jLabel2.setText("vs.");

        jugador4Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jugador4Label.setText("jLabel3");

        jugador7Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jugador7Label.setText("jLabel2");

        jLabel3.setText("vs.");

        jugador8Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jugador8Label.setText("jLabel3");

        jugador5Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jugador5Label.setText("jLabel1");

        jLabel4.setText("vs.");

        jugador6Label.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jugador6Label.setText("jLabel2");

        volverButton.setText("Volver");
        volverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverButtonMouseClicked(evt);
            }
        });

        semifinal1Jugador1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        semifinal1Jugador1.setText("jLabel5");

        jLabel5.setText("vs.");

        semifinal2Jugador1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        semifinal2Jugador1.setText("jLabel6");

        semifinal2Jugador2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        semifinal2Jugador2.setText("jLabel6");

        semifinal1Jugador2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        semifinal1Jugador2.setText("jLabel6");

        jLabel6.setText("vs.");

        jLabel7.setText("Final:");

        finalJugador1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        finalJugador1.setText("jLabel8");

        jLabel8.setText("vs");

        finalJugador2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        finalJugador2.setText("jLabel9");

        puntosJugador7.setText("-");

        puntosJugador8.setText("-");

        puntosJugador1Semifinal2.setText("-");

        puntosJugador2Semifinal2.setText("-");

        puntosJugador1Semifinal1.setText("-");

        puntosJugador2Semifinal1.setText("-");

        puntosFinal1.setText("-");

        puntosFinal2.setText("-");

        simular1Button.setText("Simular");
        simular1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simular1ButtonMouseClicked(evt);
            }
        });

        simular6Button.setText("Simular");
        simular6Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simular6ButtonMouseClicked(evt);
            }
        });

        simular2Button.setText("Simular");
        simular2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simular2ButtonMouseClicked(evt);
            }
        });

        simular5Button.setText("Simular");
        simular5Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simular5ButtonMouseClicked(evt);
            }
        });

        simular3Button.setText("Simular");
        simular3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simular3ButtonMouseClicked(evt);
            }
        });

        simular4Button.setText("Simular");
        simular4Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simular4ButtonMouseClicked(evt);
            }
        });

        simular7Button.setText("Simular");
        simular7Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simular7ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simular2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(simular7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(simular5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(simular6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(177, 177, 177)
                                        .addComponent(puntosJugador1Semifinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(117, 117, 117)
                                                .addComponent(semifinal1Jugador1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jugador1Label)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(puntosJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jugador3Label)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(puntosJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel1)
                                                            .addComponent(jugador2Label))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(puntosJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel2)
                                                            .addComponent(jugador4Label))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(puntosJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(semifinal1Jugador2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(puntosJugador2Semifinal1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(finalJugador2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(puntosJugador1Semifinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(puntosJugador2Semifinal2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(semifinal2Jugador1)
                                                    .addComponent(semifinal2Jugador2)
                                                    .addComponent(jLabel5)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(puntosFinal2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(80, 80, 80))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(simular1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(volverButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(165, 165, 165)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(puntosFinal1)
                                            .addComponent(finalJugador1))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jugador8Label)
                                                .addGap(18, 18, 18)
                                                .addComponent(puntosJugador8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(simular4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jugador7Label)
                                                .addGap(18, 18, 18)
                                                .addComponent(puntosJugador7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jugador6Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(puntosJugador6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jugador5Label)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(puntosJugador5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(simular3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(96, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simular3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simular1Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(puntosJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador1Label))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puntosJugador5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jugador5Label))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jugador3Label)
                                    .addComponent(puntosJugador3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(simular5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(simular6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(semifinal2Jugador1)
                                            .addComponent(semifinal1Jugador1)
                                            .addComponent(puntosJugador1Semifinal2)
                                            .addComponent(puntosJugador1Semifinal1))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(semifinal1Jugador2)
                                            .addComponent(puntosJugador2Semifinal1)
                                            .addComponent(semifinal2Jugador2)
                                            .addComponent(puntosJugador2Semifinal2))
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(28, 28, 28))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(puntosJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jugador2Label)
                                                .addComponent(jugador6Label))
                                            .addComponent(puntosJugador6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(76, 76, 76)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jugador7Label)
                                    .addComponent(puntosJugador7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(finalJugador1)
                        .addComponent(jLabel8)
                        .addComponent(finalJugador2)
                        .addComponent(jugador8Label)
                        .addComponent(puntosJugador8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jugador4Label)
                            .addComponent(puntosJugador4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puntosFinal1)
                    .addComponent(puntosFinal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simular2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simular4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simular7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(volverButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_volverButtonMouseClicked

    private void simular1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simular1ButtonMouseClicked
        int random1 = (int) (Math.random()*99+1);
        int random2 = (int) (Math.random()*99+1);
                
        torneo.getPartidasList().get(0).setPuntos1(random1);
        torneo.getPartidasList().get(0).setPuntos2(random2);
        torneo.getPartidasList().get(0).setFinalizada(true);
        simular1Button.setVisible(false);

        setLabels();
    }//GEN-LAST:event_simular1ButtonMouseClicked

    private void simular2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simular2ButtonMouseClicked
        int random1 = (int) (Math.random()*99+1);
        int random2 = (int) (Math.random()*99+1);
                
        torneo.getPartidasList().get(1).setPuntos1(random1);
        torneo.getPartidasList().get(1).setPuntos2(random2);
        torneo.getPartidasList().get(1).setFinalizada(true);
        simular2Button.setVisible(false);
        setLabels();
    }//GEN-LAST:event_simular2ButtonMouseClicked

    private void simular3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simular3ButtonMouseClicked
        int random1 = (int) (Math.random()*99+1);
        int random2 = (int) (Math.random()*99+1);
                
        torneo.getPartidasList().get(2).setPuntos1(random1);
        torneo.getPartidasList().get(2).setPuntos2(random2);
        torneo.getPartidasList().get(2).setFinalizada(true);
        simular3Button.setVisible(false);

        setLabels();
    }//GEN-LAST:event_simular3ButtonMouseClicked

    private void simular4ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simular4ButtonMouseClicked
        int random1 = (int) (Math.random()*99+1);
        int random2 = (int) (Math.random()*99+1);
                
        torneo.getPartidasList().get(3).setPuntos1(random1);
        torneo.getPartidasList().get(3).setPuntos2(random2);
        torneo.getPartidasList().get(3).setFinalizada(true);
        simular4Button.setVisible(false);

        setLabels();
    }//GEN-LAST:event_simular4ButtonMouseClicked

    private void simular5ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simular5ButtonMouseClicked
        int random1 = (int) (Math.random()*99+1);
        int random2 = (int) (Math.random()*99+1);
                
        torneo.getPartidasList().get(4).setPuntos1(random1);
        torneo.getPartidasList().get(4).setPuntos2(random2);
        torneo.getPartidasList().get(4).setFinalizada(true);
        simular5Button.setVisible(false);
        puntosJugador1Semifinal1.setText(String.valueOf(torneo.getPartidasList().get(4).getPuntos1()));
        puntosJugador2Semifinal1.setText(String.valueOf(torneo.getPartidasList().get(4).getPuntos2()));
        setLabels();
    }//GEN-LAST:event_simular5ButtonMouseClicked

    private void simular6ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simular6ButtonMouseClicked
        int random1 = (int) (Math.random()*99+1);
        int random2 = (int) (Math.random()*99+1);
                
        torneo.getPartidasList().get(5).setPuntos1(random1);
        torneo.getPartidasList().get(5).setPuntos2(random2);
        torneo.getPartidasList().get(5).setFinalizada(true);
        simular6Button.setVisible(false);
        puntosJugador1Semifinal2.setText(String.valueOf(torneo.getPartidasList().get(5).getPuntos1()));
        puntosJugador2Semifinal2.setText(String.valueOf(torneo.getPartidasList().get(5).getPuntos2()));
        setLabels();
    }//GEN-LAST:event_simular6ButtonMouseClicked

    private void simular7ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simular7ButtonMouseClicked
        int random1 = (int) (Math.random()*99+1);
        int random2 = (int) (Math.random()*99+1);
                
        torneo.getPartidasList().get(6).setPuntos1(random1);
        torneo.getPartidasList().get(6).setPuntos2(random2);
        torneo.getPartidasList().get(6).setFinalizada(true);
        simular7Button.setVisible(false);
        puntosFinal1.setText(String.valueOf(torneo.getPartidasList().get(6).getPuntos1()));
        puntosFinal2.setText(String.valueOf(torneo.getPartidasList().get(6).getPuntos2()));
        torneo.setFinalizado(true);
    }//GEN-LAST:event_simular7ButtonMouseClicked

     public void setTorneoSelected(Torneo tor)
    {
        torneo = tor;
    }
    
    public void setLabels ()
    {
        jugador1Label.setText(torneo.getPartidasList().get(0).getJugador1().getNombre());
        jugador2Label.setText(torneo.getPartidasList().get(0).getJugador2().getNombre());
        jugador3Label.setText(torneo.getPartidasList().get(1).getJugador1().getNombre());
        jugador4Label.setText(torneo.getPartidasList().get(1).getJugador2().getNombre());
        jugador5Label.setText(torneo.getPartidasList().get(2).getJugador1().getNombre());
        jugador6Label.setText(torneo.getPartidasList().get(2).getJugador2().getNombre());
        jugador7Label.setText(torneo.getPartidasList().get(3).getJugador1().getNombre());
        jugador8Label.setText(torneo.getPartidasList().get(3).getJugador2().getNombre());
        
        if(torneo.getPartidasList().get(0).isFinalizada())
        {
            simular1Button.setVisible(false);
            puntosJugador1.setText(String.valueOf(torneo.getPartidasList().get(0).getPuntos1()));
            puntosJugador2.setText(String.valueOf(torneo.getPartidasList().get(0).getPuntos2()));
            semifinal1Jugador1.setText(torneo.getPartidasList().get(0).ganador().getNombre());
            if(!torneo.getPartidasList().get(4).isConfigurada())
            {
                torneo.getPartidasList().get(4).setJugador1(torneo.getPartidasList().get(0).ganador());
            }
        }
        
        if(torneo.getPartidasList().get(1).isFinalizada())
        {
            simular2Button.setVisible(false);
            puntosJugador3.setText(String.valueOf(torneo.getPartidasList().get(1).getPuntos1()));
            puntosJugador4.setText(String.valueOf(torneo.getPartidasList().get(1).getPuntos2()));
            semifinal1Jugador2.setText(torneo.getPartidasList().get(1).ganador().getNombre());
            if(!torneo.getPartidasList().get(4).isConfigurada())
            {
                torneo.getPartidasList().get(4).setJugador2(torneo.getPartidasList().get(1).ganador());
            }
        }
        
        if(torneo.getPartidasList().get(2).isFinalizada())
        {
            simular3Button.setVisible(false);
            puntosJugador5.setText(String.valueOf(torneo.getPartidasList().get(2).getPuntos1()));
            puntosJugador6.setText(String.valueOf(torneo.getPartidasList().get(2).getPuntos2()));
            semifinal2Jugador1.setText(torneo.getPartidasList().get(2).ganador().getNombre());
            if(!torneo.getPartidasList().get(5).isConfigurada())
            {
                torneo.getPartidasList().get(5).setJugador1(torneo.getPartidasList().get(2).ganador());
            }
        }
        
        if(torneo.getPartidasList().get(3).isFinalizada())
        {
            simular4Button.setVisible(false);
            puntosJugador7.setText(String.valueOf(torneo.getPartidasList().get(3).getPuntos1()));
            puntosJugador8.setText(String.valueOf(torneo.getPartidasList().get(3).getPuntos2()));
            semifinal2Jugador2.setText(torneo.getPartidasList().get(3).ganador().getNombre());
            if(!torneo.getPartidasList().get(5).isConfigurada())
            {
                torneo.getPartidasList().get(5).setJugador2(torneo.getPartidasList().get(3).ganador());
            }
        }
        
        if(torneo.getPartidasList().get(0).isFinalizada() && torneo.getPartidasList().get(1).isFinalizada())
        {
            if(admin)
                simular5Button.setVisible(true);
            
            torneo.getPartidasList().get(4).setConfigurada(true);
        }
        
        if(torneo.getPartidasList().get(4).isFinalizada())
        {
            if(admin)
                simular5Button.setVisible(false);
            
            semifinal1Jugador1.setText(torneo.getPartidasList().get(4).getJugador1().getNombre());
            semifinal1Jugador2.setText(torneo.getPartidasList().get(4).getJugador2().getNombre());
            puntosJugador1Semifinal1.setText(String.valueOf(torneo.getPartidasList().get(4).getPuntos1()));
            puntosJugador2Semifinal1.setText(String.valueOf(torneo.getPartidasList().get(4).getPuntos2()));
            if(!torneo.getPartidasList().get(6).isConfigurada())
            {
                torneo.getPartidasList().get(6).setJugador1(torneo.getPartidasList().get(4).ganador());
            }
            
        }
        
        if(torneo.getPartidasList().get(2).isFinalizada() && torneo.getPartidasList().get(3).isFinalizada())
        {
            if(admin)
                simular6Button.setVisible(true);
            
            torneo.getPartidasList().get(5).setConfigurada(true);
        }
        
        if(torneo.getPartidasList().get(5).isFinalizada())
        {
            if(admin)
                simular6Button.setVisible(false);
            
            semifinal2Jugador1.setText(torneo.getPartidasList().get(5).getJugador1().getNombre());
            semifinal2Jugador2.setText(torneo.getPartidasList().get(5).getJugador2().getNombre());
            puntosJugador1Semifinal2.setText(String.valueOf(torneo.getPartidasList().get(5).getPuntos1()));
            puntosJugador2Semifinal2.setText(String.valueOf(torneo.getPartidasList().get(5).getPuntos2()));
            if(!torneo.getPartidasList().get(6).isConfigurada())
            {
                torneo.getPartidasList().get(6).setJugador2(torneo.getPartidasList().get(5).ganador());
            }
            
        }
        
        if(torneo.getPartidasList().get(4).isFinalizada() && torneo.getPartidasList().get(5).isFinalizada())
        {
            if(admin)
                simular7Button.setVisible(true);
            
            finalJugador1.setText(torneo.getPartidasList().get(6).getJugador1().getNombre());
            finalJugador2.setText(torneo.getPartidasList().get(6).getJugador2().getNombre());
            torneo.getPartidasList().get(6).setConfigurada(true);
        }
        
        if(torneo.getPartidasList().get(6).isFinalizada())
        {
            if(admin)
                simular7Button.setVisible(false);
            
            finalJugador1.setText(torneo.getPartidasList().get(6).getJugador1().getNombre());
            finalJugador1.setText(torneo.getPartidasList().get(6).getJugador2().getNombre());
            puntosFinal1.setText(String.valueOf(torneo.getPartidasList().get(6).getPuntos1()));
            puntosFinal2.setText(String.valueOf(torneo.getPartidasList().get(6).getPuntos2()));
            
            torneo.setFinalizado(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finalJugador1;
    private javax.swing.JLabel finalJugador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jugador1Label;
    private javax.swing.JLabel jugador2Label;
    private javax.swing.JLabel jugador3Label;
    private javax.swing.JLabel jugador4Label;
    private javax.swing.JLabel jugador5Label;
    private javax.swing.JLabel jugador6Label;
    private javax.swing.JLabel jugador7Label;
    private javax.swing.JLabel jugador8Label;
    private javax.swing.JLabel puntosFinal1;
    private javax.swing.JLabel puntosFinal2;
    private javax.swing.JLabel puntosJugador1;
    private javax.swing.JLabel puntosJugador1Semifinal1;
    private javax.swing.JLabel puntosJugador1Semifinal2;
    private javax.swing.JLabel puntosJugador2;
    private javax.swing.JLabel puntosJugador2Semifinal1;
    private javax.swing.JLabel puntosJugador2Semifinal2;
    private javax.swing.JLabel puntosJugador3;
    private javax.swing.JLabel puntosJugador4;
    private javax.swing.JLabel puntosJugador5;
    private javax.swing.JLabel puntosJugador6;
    private javax.swing.JLabel puntosJugador7;
    private javax.swing.JLabel puntosJugador8;
    private javax.swing.JLabel semifinal1Jugador1;
    private javax.swing.JLabel semifinal1Jugador2;
    private javax.swing.JLabel semifinal2Jugador1;
    private javax.swing.JLabel semifinal2Jugador2;
    private javax.swing.JButton simular1Button;
    private javax.swing.JButton simular2Button;
    private javax.swing.JButton simular3Button;
    private javax.swing.JButton simular4Button;
    private javax.swing.JButton simular5Button;
    private javax.swing.JButton simular6Button;
    private javax.swing.JButton simular7Button;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
    private ConfigurarTorneo configurarTorneo;
    private Torneo torneo;
    private boolean admin;
}
