/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Club;
import Clases.Gerente;
import Clases.Usuario;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author enrique
 */
public class GestionarGerente extends javax.swing.JFrame {

    /**
     * Creates new form GesetionarGerente
     */
    public GestionarGerente(AdministracionClubs _administracionClubs) {
        initComponents();
        this.administracionClubs = _administracionClubs;
        queClubLabel.setVisible(false);
        cambiarGerenteList.setVisible(false);
        confirmarCambioButton.setVisible(false);
        exitoLabel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverButton = new javax.swing.JButton();
        gerente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        historialList = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clubName = new javax.swing.JLabel();
        nominaLabel = new javax.swing.JLabel();
        irpfLabel = new javax.swing.JLabel();
        cambiarClubGerente = new javax.swing.JButton();
        queClubLabel = new javax.swing.JLabel();
        cambiarGerenteList = new java.awt.List();
        confirmarCambioButton = new javax.swing.JButton();
        exitoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nacimientoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        volverButton.setText("Volver");
        volverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverButtonMouseClicked(evt);
            }
        });

        gerente.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        gerente.setText("jLabel2");

        jLabel1.setText("Historial:");

        jLabel2.setText("Nómina:");

        jLabel3.setText("IRPF:");

        clubName.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        clubName.setText("jLabel4");

        nominaLabel.setText("jLabel4");

        irpfLabel.setText("jLabel4");

        cambiarClubGerente.setText("Cambiar gerente de club");
        cambiarClubGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiarClubGerenteMouseClicked(evt);
            }
        });

        queClubLabel.setText("¿A qué club deseas cambiarlo?");

        cambiarGerenteList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cambiarGerenteListItemStateChanged(evt);
            }
        });

        confirmarCambioButton.setText("Confirmar cambio");
        confirmarCambioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarCambioButtonMouseClicked(evt);
            }
        });

        exitoLabel.setText("Cambio realizado con éxito!");

        jLabel4.setText("Fecha de nacimiento:");

        nacimientoLabel.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerente)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(historialList, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(queClubLabel)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(cambiarClubGerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(cambiarGerenteList, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clubName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(nominaLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(irpfLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nacimientoLabel))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volverButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmarCambioButton)
                    .addComponent(exitoLabel))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gerente)
                    .addComponent(clubName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(queClubLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(nominaLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(irpfLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(nacimientoLabel))
                                        .addGap(26, 26, 26)
                                        .addComponent(cambiarClubGerente))
                                    .addComponent(historialList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 42, Short.MAX_VALUE)
                                .addComponent(volverButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(confirmarCambioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitoLabel)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cambiarGerenteList, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMouseClicked
        this.setVisible(false);
        administracionClubs.setClubes(clubesList);
        administracionClubs.setVisible(true);
    }//GEN-LAST:event_volverButtonMouseClicked

    private void cambiarClubGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarClubGerenteMouseClicked
        queClubLabel.setVisible(true);
        
        cambiarGerenteList.setVisible(true);
        confirmarCambioButton.setVisible(true);
        
    }//GEN-LAST:event_cambiarClubGerenteMouseClicked

    private void cambiarGerenteListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cambiarGerenteListItemStateChanged
       clubSelected = clubesList.get(cambiarGerenteList.getSelectedIndex());
    }//GEN-LAST:event_cambiarGerenteListItemStateChanged

    private void confirmarCambioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarCambioButtonMouseClicked
        if (clubSelected == null)
            JOptionPane.showMessageDialog(null, "Selecciona un club");
        else
        {
            club.getGerente().getHistorico().add(clubSelected.getNombre());
            clubSelected.getGerente().borrarDatos();
            gerenteAux= clubSelected.getGerente();
            clubSelected.setGerente(club.getGerente());
            club.setGerente(gerenteAux);
            System.out.println("**********AÑADIDO***********");
            clubSelected.getGerente().verDatos();
            club.getGerente().verDatos();
            //exitoLabel.setVisible(true);
            this.setVisible(false);
            administracionClubs.setClubes(clubesList);
            administracionClubs.setLabels();
            administracionClubs.setVisible(true);
        }
    }//GEN-LAST:event_confirmarCambioButtonMouseClicked

    public void setClubes(ArrayList<Club> clubes)
    {
        clubesList = clubes;    
    }
    
    public void setClub(Club _club)
    {
        club = _club;
    }
    
    public String ConvertirFecha(Date fecha)
    {
        String dia = new String("");
        String mes = new String("");
        String anyo = new String("");
        
        dia = Integer.toString(fecha.getDate());
        mes = Integer.toString(fecha.getMonth() + 1);
        anyo = Integer.toString(fecha.getYear() + 1900);
        
        return dia+"/"+mes+"/"+anyo;
    }
    
    public void setLabels()
    {
        gerente.setText(club.getGerente().getNombre() + " " + club.getGerente().getApellidos());
        //clubgerente.setText(clubesList.get(clubOnline).getGerente().getHistorico().get(0));
        historialList.removeAll();
        for (int i = 0; i < club.getGerente().getHistorico().size(); i++)
        {
                historialList.add(club.getGerente().getHistorico().get(i), i);
        }
        cambiarGerenteList.removeAll();
        for (int i = 0; i < clubesList.size(); i++)
        {
                cambiarGerenteList.add(clubesList.get(i).getNombre(), i);
        }
        
        clubName.setText(club.getNombre());
        nominaLabel.setText(String.valueOf(club.getGerente().getNomina()));
        irpfLabel.setText(String.valueOf(club.getGerente().getIrpf()));
        nacimientoLabel.setText(ConvertirFecha(club.getGerente().getFechaNacimiento()));
        queClubLabel.setVisible(false);
        cambiarGerenteList.setVisible(false);
        confirmarCambioButton.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarClubGerente;
    private java.awt.List cambiarGerenteList;
    private javax.swing.JLabel clubName;
    private javax.swing.JButton confirmarCambioButton;
    private javax.swing.JLabel exitoLabel;
    private javax.swing.JLabel gerente;
    private java.awt.List historialList;
    private javax.swing.JLabel irpfLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nacimientoLabel;
    private javax.swing.JLabel nominaLabel;
    private javax.swing.JLabel queClubLabel;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Club> clubesList = new ArrayList<Club>();
    private AdministracionClubs administracionClubs;
    private Club club;
    private Club clubSelected;
    private Gerente gerenteAux;
}
