/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.ArrayList;

/**
 *
 * @author santi
 */
public class MenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario(Inicio inicio) {
        initComponents();
        this.inicio = inicio;
        this.datosClub = new DatosClub(this);
        this.introduceResultados = new IntroduceResultados(this);
        this.reservaEntrenamiento = new ReservaEntrenamiento(this);
        this.datosUsuario = new DatosUsuario(this);
  
        this.datosList= inicio.getDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReservaEntrenamiento = new javax.swing.JButton();
        IntroducirResultados = new javax.swing.JButton();
        FinalizarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MiClub = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MisDatos = new javax.swing.JButton();
        usuarioLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ReservaEntrenamiento.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        ReservaEntrenamiento.setText("Reserva entrenamiento");
        ReservaEntrenamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservaEntrenamientoMouseClicked(evt);
            }
        });

        IntroducirResultados.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        IntroducirResultados.setText("Introduce resultados");
        IntroducirResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IntroducirResultadosMouseClicked(evt);
            }
        });

        FinalizarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion.png"))); // NOI18N
        FinalizarSesion.setText("Finalizar sesión");
        FinalizarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinalizarSesionMouseClicked(evt);
            }
        });
        FinalizarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarSesionActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Bienvenido,");

        MiClub.setText("Mi club");
        MiClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiClubMouseClicked(evt);
            }
        });
        MiClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiClubActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rey.png"))); // NOI18N

        MisDatos.setText("Mis datos");
        MisDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MisDatosMouseClicked(evt);
            }
        });

        usuarioLabel.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        usuarioLabel.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FinalizarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MiClub)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(IntroducirResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReservaEntrenamiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MisDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FinalizarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(usuarioLabel))
                .addGap(18, 18, 18)
                .addComponent(MiClub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(MisDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ReservaEntrenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IntroducirResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReservaEntrenamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservaEntrenamientoMouseClicked
        this.setVisible(false);
        reservaEntrenamiento.setVisible(true);
    }//GEN-LAST:event_ReservaEntrenamientoMouseClicked

    private void IntroducirResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IntroducirResultadosMouseClicked
        this.setVisible(false);
        introduceResultados.setVisible(true);
    }//GEN-LAST:event_IntroducirResultadosMouseClicked

    private void FinalizarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalizarSesionMouseClicked
        this.setVisible(false);
        inicio.setDatos(datosList);
        inicio.setVisible(true);
    }//GEN-LAST:event_FinalizarSesionMouseClicked

    private void MiClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiClubMouseClicked
        //this.setVisible(false);
        datosClub.setVisible(true);
    }//GEN-LAST:event_MiClubMouseClicked

    private void FinalizarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarSesionActionPerformed

    private void MiClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiClubActionPerformed

    private void MisDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MisDatosMouseClicked
        datosUsuario.setDatos(datosList);
        datosUsuario.setUserOnline(userOnline);
        datosUsuario.setLabels();
        datosUsuario.setVisible(true);
    }//GEN-LAST:event_MisDatosMouseClicked
    
    public void setDatos(ArrayList<Usuario> datos)
    {
        datosList = datos;    
    }
    
    public void setUserOnline (int i)
    {
        userOnline = i;
    }
    public void setLabels ()
    {
        usuarioLabel.setText(datosList.get(userOnline).getId());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinalizarSesion;
    private javax.swing.JButton IntroducirResultados;
    private javax.swing.JButton MiClub;
    private javax.swing.JButton MisDatos;
    private javax.swing.JButton ReservaEntrenamiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
    private Inicio inicio;
    private DatosClub datosClub;
    private ReservaEntrenamiento reservaEntrenamiento;
    private IntroduceResultados introduceResultados;
    private DatosUsuario datosUsuario;
    private ArrayList<Usuario> datosList = new ArrayList<Usuario>();
    private int userOnline;
}
