/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.ArrayList;

/**
 *
 * @author enrique
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PanelAdmin
     */
    public MenuAdmin(Inicio inicio) {
        initComponents();
        this.inicio = inicio;
        this.datosClub = new DatosClub(this);
        this.introduceResultados = new IntroduceResultados(this);
        this.reservaEntrenamiento = new ReservaEntrenamiento(this);
        this.datosUsuario = new DatosUsuario(this);      
        this.administracionClubs = new AdministracionClubs(this);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        realizarReserva = new javax.swing.JButton();
        RegistrarDatosPartida = new javax.swing.JButton();
        AsignarSede = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FinalizarSesion = new javax.swing.JButton();
        MiClub = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AdministrarClubs = new javax.swing.JButton();
        usuarioLabel = new javax.swing.JLabel();
        MisDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        realizarReserva.setText("Realizar reserva");
        realizarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                realizarReservaMouseClicked(evt);
            }
        });
        realizarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarReservaActionPerformed(evt);
            }
        });

        RegistrarDatosPartida.setText("Registrar datos partida");
        RegistrarDatosPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarDatosPartidaMouseClicked(evt);
            }
        });

        AsignarSede.setText("Asignar sede a partida");
        AsignarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarSedeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Bienvenido,");

        FinalizarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CerrarSesion.png"))); // NOI18N
        FinalizarSesion.setText("Finalizar sesión");
        FinalizarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FinalizarSesionMouseClicked(evt);
            }
        });

        MiClub.setText("Mi club");
        MiClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiClubMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ReyGold.png"))); // NOI18N

        AdministrarClubs.setText("Administrar clubs");
        AdministrarClubs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministrarClubsMouseClicked(evt);
            }
        });

        usuarioLabel.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        usuarioLabel.setText("jLabel2");

        MisDatos.setText("Mis datos");
        MisDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MisDatosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usuarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FinalizarSesion)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MisDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MiClub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AdministrarClubs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegistrarDatosPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(realizarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(AsignarSede, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                        .addGap(0, 74, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(usuarioLabel)))
                    .addComponent(FinalizarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MiClub))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(realizarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MisDatos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegistrarDatosPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AsignarSede, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdministrarClubs, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AsignarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsignarSedeActionPerformed

    private void realizarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarReservaMouseClicked
        this.setVisible(false);
        reservaEntrenamiento.setVisible(true);
    }//GEN-LAST:event_realizarReservaMouseClicked

    private void RegistrarDatosPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarDatosPartidaMouseClicked
        this.setVisible(false);
        introduceResultados.setVisible(true);
    }//GEN-LAST:event_RegistrarDatosPartidaMouseClicked

    private void FinalizarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FinalizarSesionMouseClicked
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_FinalizarSesionMouseClicked

    private void MiClubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiClubMouseClicked
        //this.setVisible(false);
        datosClub.setVisible(true);
    }//GEN-LAST:event_MiClubMouseClicked

    private void realizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarReservaActionPerformed

    private void AdministrarClubsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrarClubsMouseClicked
        this.setVisible(false);
        administracionClubs.setVisible(true);
    }//GEN-LAST:event_AdministrarClubsMouseClicked

    private void MisDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MisDatosMouseClicked
        datosUsuario.setDatos(datosList);
        datosUsuario.setUserOnline(userOnline);
        datosUsuario.setLabels();
        datosUsuario.setVisible(true);
    }//GEN-LAST:event_MisDatosMouseClicked

    public void setDatos(ArrayList<Usuario> datos)
    {
        datosList.addAll(datos);    
    }
    
    public void setUserOnline (int i)
    {
        userOnline = i;
    }
    public void setLabels ()
    {
        usuarioLabel.setText(datosList.get(userOnline).getId());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdministrarClubs;
    private javax.swing.JButton AsignarSede;
    private javax.swing.JButton FinalizarSesion;
    private javax.swing.JButton MiClub;
    private javax.swing.JButton MisDatos;
    private javax.swing.JButton RegistrarDatosPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton realizarReserva;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
    private Inicio inicio;
    private DatosClub datosClub;
    private ReservaEntrenamiento reservaEntrenamiento;
    private IntroduceResultados introduceResultados;
    private DatosUsuario datosUsuario;
    private AdministracionClubs administracionClubs;
    private ArrayList<Usuario> datosList = new ArrayList<Usuario>();
    private int userOnline;
}
