/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Club;
import Clases.Torneo;
import Clases.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author enrique
 */
public class TorneosUser extends javax.swing.JFrame {

    /**
     * Creates new form TorneosUser
     */
    public TorneosUser(MenuUsuario menuUsuario) {
        initComponents();
        this.menuUsuario = menuUsuario;
        this.cuadro4 = new Cuadro4();
        this.cuadro8 = new Cuadro8 ();
        verTorneoButton.setVisible(false);
        exitoLabel.setVisible(false);
        maxLabel.setVisible(false);
        finalizadoLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volverButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        torneosJList = new java.awt.List();
        apuntarseButton = new javax.swing.JButton();
        verTorneoButton = new javax.swing.JButton();
        exitoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numJugadoresLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numJugadoresRequeridosLabel = new javax.swing.JLabel();
        finalizadoLabel = new javax.swing.JLabel();
        maxLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        federacionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        volverButton.setText("Volver");
        volverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Torneos en curso:");

        torneosJList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                torneosJListItemStateChanged(evt);
            }
        });

        apuntarseButton.setText("Apuntarse");
        apuntarseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apuntarseButtonMouseClicked(evt);
            }
        });

        verTorneoButton.setText("Ver torneo");
        verTorneoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verTorneoButtonMouseClicked(evt);
            }
        });

        exitoLabel.setText("Apuntado con éxito!");

        jLabel3.setText("Número de jugadores:");

        numJugadoresLabel.setText("jLabel4");

        jLabel2.setText("Número de jugadores requeridos:");

        numJugadoresRequeridosLabel.setText("jLabel4");

        finalizadoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        finalizadoLabel.setText("Torneo finalizado");

        maxLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        maxLabel.setText("Número máximo de participantes alcanzado");

        jLabel4.setText("Federación organizadora:");

        federacionLabel.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(volverButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(torneosJList, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addGap(33, 33, 33)
                                .addComponent(federacionLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)
                                .addComponent(numJugadoresLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numJugadoresRequeridosLabel))
                            .addComponent(finalizadoLabel)
                            .addComponent(maxLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(apuntarseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verTorneoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exitoLabel)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(torneosJList, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(numJugadoresLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(numJugadoresRequeridosLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(federacionLabel))
                        .addGap(3, 3, 3)
                        .addComponent(finalizadoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maxLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apuntarseButton)
                    .addComponent(verTorneoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(volverButton)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverButtonMouseClicked
        this.setVisible(false);
        menuUsuario.setTorneos(torneosList);
        menuUsuario.setELO();
        menuUsuario.setVisible(true);
    }//GEN-LAST:event_volverButtonMouseClicked

    private void verTorneoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verTorneoButtonMouseClicked
        if(torneo.getNumJugadores() == 4)
        {
            cuadro4.setTorneoSelected(torneo);
            cuadro4.setLabels();
            cuadro4.setVisible(true);
        }
        else if(torneo.getNumJugadores() == 8)
        {
            cuadro8.setTorneoSelected(torneo);
            cuadro8.setLabels();
            cuadro8.setVisible(true);
        }
    }//GEN-LAST:event_verTorneoButtonMouseClicked

    private void torneosJListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_torneosJListItemStateChanged
        numTorneoSelected = torneosJList.getSelectedIndex();
        torneo = torneosList.get(numTorneoSelected);
        setLabels();
    }//GEN-LAST:event_torneosJListItemStateChanged

    private void apuntarseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apuntarseButtonMouseClicked
        if(torneo.getJugadoresList().contains(usuario))
            JOptionPane.showMessageDialog(null, "Ya te has apuntado");
        else if (torneo.getFederacion().getClubesList().contains(club))
        {
            torneo.getJugadoresList().add(usuario);
            exitoLabel.setVisible(true);
            numJugadoresLabel.setText(String.valueOf(torneo.getJugadoresList().size()));
            if(torneo.getNumJugadores() == torneo.getJugadoresList().size())
            {
                System.out.println("FLAG");
                torneo.Iniciar();
                torneo.setInscripcionAbierta(false);
            }
            setLabels();
        }
        else
            JOptionPane.showMessageDialog(null, "Tu club no pertenece a la federación organizadora");
        
    }//GEN-LAST:event_apuntarseButtonMouseClicked

    public void setUsuario(Usuario usu)
    {
        usuario = usu;
    }
    
    public void setClub(Club _club)
    {
        club = _club;
    }
    
    public void setTorneos(ArrayList<Torneo> torneos)
    {
        torneosList = torneos;
        torneo = torneosList.get(0);
    }
    
    public void setLabels ()
    {
        torneosJList.removeAll();
        for(int i = 0; i < torneosList.size(); i++)
        {
            torneosJList.add(torneosList.get(i).getNombre(), i);
        }
        
        numJugadoresLabel.setText(String.valueOf(torneo.getJugadoresList().size()));
        numJugadoresRequeridosLabel.setText(String.valueOf(torneo.getNumJugadores()));
        federacionLabel.setText(torneo.getFederacion().getProvincia());
        
        if(torneo.isFinalizado())
            finalizadoLabel.setVisible(true);
        else
            finalizadoLabel.setVisible(false);
        
        if(!torneo.isInscripcionAbierta())
        {
            apuntarseButton.setVisible(false);
            maxLabel.setVisible(true);
            verTorneoButton.setVisible(true);
        }
        else
        {
            apuntarseButton.setVisible(true);
            maxLabel.setVisible(false);
            verTorneoButton.setVisible(false);
        }        
        exitoLabel.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apuntarseButton;
    private javax.swing.JLabel exitoLabel;
    private javax.swing.JLabel federacionLabel;
    private javax.swing.JLabel finalizadoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel maxLabel;
    private javax.swing.JLabel numJugadoresLabel;
    private javax.swing.JLabel numJugadoresRequeridosLabel;
    private java.awt.List torneosJList;
    private javax.swing.JButton verTorneoButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
    private MenuUsuario menuUsuario;
    private Cuadro4 cuadro4;
    private Cuadro8 cuadro8;
    private ArrayList<Torneo> torneosList = new ArrayList<Torneo>();
    private Usuario usuario;
    private Club club;
    private int numTorneoSelected;
    private Torneo torneo;
}

